"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.blobTests = exports.dbSetupTests = exports.queriesTests = exports.runTests = void 0;
var MochaSetup_1 = require("./MochaSetup");
Object.defineProperty(exports, "runTests", { enumerable: true, get: function () { return MochaSetup_1.runTests; } });
var queries_spec_1 = require("./queries.spec");
Object.defineProperty(exports, "queriesTests", { enumerable: true, get: function () { return queries_spec_1.queriesTests; } });
var dbsetup_spec_1 = require("./dbsetup.spec");
Object.defineProperty(exports, "dbSetupTests", { enumerable: true, get: function () { return dbsetup_spec_1.dbSetupTests; } });
var blob_spec_1 = require("./blob.spec");
Object.defineProperty(exports, "blobTests", { enumerable: true, get: function () { return blob_spec_1.blobTests; } });
