name: Bug Report
description: File a bug report
title: '[Bug]: '
body:
  - type: markdown
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Before filling a report, make sure you have read the documentation and you are on the latest version of the package. If the issue is non-trivial YOU MUST CREATE A REPRODUCIBLE EXAMPLE. Otherwise the issue will be closed.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of op-sqlite are you using? Have you tried the latest version?
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: React Native Version
      description: What version of React Native version are you using
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Reproducible example
      description: Please post a repo with a minimum reproducible example
    validations:
      required: true
