name: Feature Request
description: Open a feature request
title: '[Request]: '
body:
  - type: textarea
    attributes:
      label: What do you need?
      placeholder: - Depending on your requirement a paid sponsorship might be necessary.\n- Be specific\n- Make sure you already updated to the latest version and checked the documentation
    validations:
      required: true
