name: Feature Request
description: Open a feature request
title: '[Request]: '
body:
  - type: textarea
    attributes:
      label: What do you need?
      placeholder: Please be specific, also bear in mind depending on your requirement a paid sponsorship might be necessary.
    validations:
      required: true
