// AutolinkedNativeModules.g.cpp contents generated by "npx @react-native-community/cli autolink-windows"
// clang-format off
#include "pch.h"
#include "AutolinkedNativeModules.g.h"

// Includes from @op-engineering/op-sqlite
#include <winrt/OpSqlite.h>

// Includes from react-native-restart
#include <winrt/ReactNativeRestart.h>

namespace winrt::Microsoft::ReactNative
{

void RegisterAutolinkedNativeModulePackages(winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::ReactNative::IReactPackageProvider> const& packageProviders)
{ 
    // IReactPackageProviders from @op-engineering/op-sqlite
    packageProviders.Append(winrt::OpSqlite::ReactPackageProvider());
    // IReactPackageProviders from react-native-restart
    packageProviders.Append(winrt::ReactNativeRestart::ReactPackageProvider());
}

}
