name: Windows CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'windows/**'
      - 'cpp/**'
      - '.github/workflows/windows.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'windows/**'
      - 'cpp/**'
      - '.github/workflows/windows.yml'

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        platform: [x64, x86]
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        yarn install
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Restore NuGet packages
      run: nuget restore windows\OPSQLite.sln
      
    - name: Build Windows module
      run: |
        msbuild windows\OPSQLite.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-build-${{ matrix.platform }}-${{ matrix.configuration }}
        path: windows/OPSQLite/${{ matrix.platform }}/${{ matrix.configuration }}/OPSQLite.dll

  test:
    needs: build
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        yarn install
        cd example
        yarn install
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Build Debug x64
      run: |
        msbuild windows\OPSQLite.sln /p:Configuration=Debug /p:Platform=x64
        
    - name: Run tests
      run: |
        cd example
        yarn test:windows
      continue-on-error: true # Continue even if tests fail for now
